name: Run test suite

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Start containers
      run: docker-compose -f "docker-compose-test.yaml" up -d --build
    - name: Run django entrypoint
      run: docker exec django4importer /bin/sh -c "sh /usr/src/importer/entrypoint_test.sh"
    - name: Run geonode-importer tests
      run: docker exec django4importer /bin/sh -c "sh /usr/src/importer/runtest.sh"
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: /usr/src/importer/.coverage
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md        
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-test.yaml" down